db = db.getSiblingDB('marketplace')
db.createCollection('accounts')
db.createCollection('account_roles')
db.createCollection('email_verifications')
db.createCollection('listings')
db.createCollection('listing_images')
db.createCollection('chats')
db.createCollection('chat_participants')
db.createCollection('messages')
db.createCollection('refresh_tokens')
db.accounts.createIndex({ email: 1 }, { unique: true })
db.accounts.createIndex({ username: 1 }, { unique: true })
db.account_roles.createIndex({ account_id: 1, role: 1 }, { unique: true })
db.email_verifications.createIndex({ token: 1 }, { unique: true })
db.listings.createIndex({ seller_id: 1 })
db.listing_images.createIndex({ listing_id: 1, position: 1 }, { unique: true })
db.chat_participants.createIndex({ chat_id: 1, account_id: 1 }, { unique: true })
db.messages.createIndex({ chat_id: 1, sent_at: -1 })
db.refresh_tokens.createIndex({ token_hash: 1 }, { unique: true })
